Add Dockerfile and workflows to build images
musaprg/annict-epgstation-connector pull request #52
Opened 2023-06-29 16:30 UTC by tsuzu

2023-06-29 16:35 UTC, tsuzu commented
Github Actions don't run....

2023-06-29 17:00 UTC, tsuzu commented on .github/workflows/docker.yml
> +      packages: write
to push images to ghcr.io

2023-06-30 03:38 UTC, tsuzu commented
Should disable pushing images on PRs?

2023-06-30 03:39 UTC, musaprg commented
I'd say this should be disabled for now. I'm going to check later if it's possible or not 🙂

2023-06-30 03:41 UTC, musaprg requested changes
Pushing GHCR for PR isn't working properly due to a token issue. Could you remove it for now?

2023-06-30 03:41 UTC, musaprg commented on .github/workflows/docker.yml
> +  pull_request:
```suggestion
```

2023-06-30 03:46 UTC, musaprg approved these changes
LGTM. Thank you!

2023-06-30 03:46 UTC, merged